services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      - ./Alerts.yml:/etc/prometheus/Alerts.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - network_monitoring
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - network_monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - network_monitoring
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./secrets/telegram_bot_token:/etc/alertmanager/secrets/telegram_bot_token:ro
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    networks:
      - network_monitoring

  process_exporter:
    image: ncabatoff/process-exporter:latest
    container_name: process_exporter
    hostname: process_exporter
    ports:
      - "9256:9256"
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - ./process-exporter.yml:/config/config.yml:ro
    command:
      - '-procfs=/host/proc'
      - '-config.path=/config/config.yml'
    networks:
      - network_monitoring
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - network_monitoring

volumes:
  grafana-storage:
  prometheus-data:

networks:
  network_monitoring: